In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat, savemat
import pandas as pd
import scipy.special as SS
import scipy.stats as SSA
import copy
import random
import math
from sklearn.model_selection import ParameterGrid

In [35]:
overrs = np.arange(0.1, 10, 1)

In [44]:
temp = [0.1, 1, 10, 20, 30, 40]
temp.reverse()
overrs = np.array(temp)

In [45]:
1/overrs

array([ 0.025     ,  0.03333333,  0.05      ,  0.1       ,  1.        ,
       10.        ])

In [51]:
1/0.5

2.0

In [11]:
rs = np.arange(0.01, 1, 0.02)

In [46]:
rs

array([0.01, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13, 0.15, 0.17, 0.19, 0.21,
       0.23, 0.25, 0.27, 0.29, 0.31, 0.33, 0.35, 0.37, 0.39, 0.41, 0.43,
       0.45, 0.47, 0.49, 0.51, 0.53, 0.55, 0.57, 0.59, 0.61, 0.63, 0.65,
       0.67, 0.69, 0.71, 0.73, 0.75, 0.77, 0.79, 0.81, 0.83, 0.85, 0.87,
       0.89, 0.91, 0.93, 0.95, 0.97, 0.99])

In [55]:
rs[[0,1,2,3,4,5,6,25,49]]

array([0.01, 0.03, 0.05, 0.07, 0.09, 0.11, 0.13, 0.51, 0.99])

In [3]:
    rs = np.arange(0.01, 1, 0.02)
    rs_selected = [0,1,2,3,4,5,6,25,49] ### select some r values
    rs = rs[rs_selected]
    R0s = np.arange(1.5, 6.5, 0.1)
    R0s = R0s[7:] ### finish the rest of R0 values
    param_grid = {'R0': R0s, 'r' : rs}
    grid = ParameterGrid(param_grid)
    para_dict = list(grid)

In [4]:
para_dict[:386]

[{'R0': 2.2000000000000006, 'r': 0.01},
 {'R0': 2.2000000000000006, 'r': 0.03},
 {'R0': 2.2000000000000006, 'r': 0.049999999999999996},
 {'R0': 2.2000000000000006, 'r': 0.06999999999999999},
 {'R0': 2.2000000000000006, 'r': 0.08999999999999998},
 {'R0': 2.2000000000000006, 'r': 0.10999999999999997},
 {'R0': 2.2000000000000006, 'r': 0.12999999999999998},
 {'R0': 2.2000000000000006, 'r': 0.5099999999999999},
 {'R0': 2.2000000000000006, 'r': 0.9899999999999999},
 {'R0': 2.3000000000000007, 'r': 0.01},
 {'R0': 2.3000000000000007, 'r': 0.03},
 {'R0': 2.3000000000000007, 'r': 0.049999999999999996},
 {'R0': 2.3000000000000007, 'r': 0.06999999999999999},
 {'R0': 2.3000000000000007, 'r': 0.08999999999999998},
 {'R0': 2.3000000000000007, 'r': 0.10999999999999997},
 {'R0': 2.3000000000000007, 'r': 0.12999999999999998},
 {'R0': 2.3000000000000007, 'r': 0.5099999999999999},
 {'R0': 2.3000000000000007, 'r': 0.9899999999999999},
 {'R0': 2.400000000000001, 'r': 0.01},
 {'R0': 2.400000000000001, 'r': 0

In [5]:
len(para_dict)

387

In [71]:
para_dict[386]

{'R0': 6.400000000000004, 'r': 0.9899999999999999}